#include <thread>
#include <enl/platform.h>
#include <enl/assert.h>
#include <glm/fwd.hpp>
#include <print.h>
#include "globals.h"
#include "baseentity.h"
#include "entityfactory.h"
#include "entsys.h"
